version: '3.8'
services: 
    app:
        build: ./app/
        volumes: 
            - ./app/:/app/
        container_name: rl_server1
        ports: 
            - 5001:5001
        environment: 
            PORT: 5001
            FLASK_DEBUG: 1
            IS_LEADER : "True"

    app1:
        build: ./app/
        volumes: 
            - ./app1/:/app/
        container_name: rl_server2
        ports: 
            - 5002:5002
        environment: 
            PORT: 5002
            FLASK_DEBUG: 1
            IS_LEADER : "False"

    app2:
        build: ./app/
        volumes: 
            - ./app2/:/app/
        container_name: rl_server3
        ports: 
            - 5003:5003
        environment: 
            PORT: 5003
            FLASK_DEBUG: 1
            IS_LEADER : "False"