# States
FOLLOWER = 'FOLLOWER'
CANDIDATE = 'CANDIDATE'
LEADER = 'LEADER'

# Requests
APPEND_RPC = 'APPEND_RPC'
VOTE_REQUEST = 'VOTE_REQUEST'
VOTE_ACK = 'VOTE_ACK'
CONVERT_FOLLOWER = 'CONVERT_FOLLOWER'
TIMEOUT = 'TIMEOUT'
SHUTDOWN = 'SHUTDOWN'
LEADER_INFO = 'LEADER_INFO'
STORE = 'STORE'
RETRIEVE = 'RETRIEVE'
COMMITED_LOGS = 'COMMITED_LOGS'
COMMITED_SUCCESSFULLY = 'COMMITED_SUCCESSFULLY'
APPEND_REPLY = 'APPEND_REPLY'
RETRIEVE_FOLLOWER_LOG = 'RETRIEVE_FOLLOWER_LOG'
